import { basePalette, chartPalette } from './constants'
import {
  ART_THEME_PRESETS,
  createArtAccentPalette,
  createArtBasePalette,
  createArtChartPalette,
  createArtStylePreset
} from './themes'
import type {
  ThemeAccentPalette,
  ThemeBasePalette,
  ThemeChartPalette,
  ThemeMenuTokens,
  ThemeRadiusOption,
  ThemeSemanticTokens,
  ThemeStylePreset
} from './types'

export const DEFAULT_THEME_SEMANTIC_TOKENS: ThemeSemanticTokens & ThemeMenuTokens = {
  themeBaseContent: '#323251',
  themeBaseContentLight: '#323251',
  themeBaseContentDark: '#e3e3e8',
  themePrimary: '#377dff',
  themePrimaryLight: '#377dff',
  themePrimaryDark: '#377dff',
  themePrimaryContent: '#ffffff',
  themePrimaryContentLight: '#ffffff',
  themePrimaryContentDark: '#ffffff',
  themeSecondary: '#00B7FF',
  themeSecondaryContent: '#06283a',
  themeAccent: '#14b8a6',
  themeAccentContent: '#022c22',
  themeNeutral: '#3f3f46',
  themeNeutralContent: '#f4f4f5',
  themeInfo: '#6e7c8c',
  themeInfoContent: '#082f49',
  themeSuccess: '#00d89f',
  themeSuccessContent: '#052e16',
  themeWarning: '#f59e0b',
  themeWarningContent: '#451a03',
  themeError: '#ef4444',
  themeErrorContent: '#450a0a',
  themeMenuHoverMixLight: '8%',
  themeMenuActiveBgMixLight: '14%'
}

export const THEME_BASE_PALETTES: ThemeBasePalette[] = [
  {
    id: 'neutral',
    name: 'Neutral',
    description: '干净中性，适合大部分业务后台',
    swatch: '#b8b8b8',
    themeSurfaceBgLight: '#fafbfc',
    themeSurfaceBgDark: '#070707',
    themeSurfaceBoxLight: '#ffffff',
    themeSurfaceBoxDark: '#161618',
    themeBorderLight: '#e3e8ee',
    themeBorderDark: 'rgba(255, 255, 255, 0.1)',
    themeBorderDashedLight: '#d4d4dc',
    themeBorderDashedDark: '#363843'
  },
  {
    id: 'stone',
    name: 'Stone',
    description: '暖灰纸感，适合内容和运营场景',
    swatch: '#000000',
    themeSurfaceBgLight: '#FCFAF8',
    themeSurfaceBgDark: '#17110d',
    themeSurfaceBoxLight: '#fffdfa',
    themeSurfaceBoxDark: '#201C1A',
    themeBorderLight: '#EDE6DC',
    themeBorderDark: 'rgba(251, 146, 60, 0.1)',
    themeBorderDashedLight: '#d8c7b6',
    themeBorderDashedDark: 'rgba(251, 146, 60, 0.12)'
  },
  {
    id: 'zinc',
    name: 'Zinc',
    description: '高对比控制台质感',
    swatch: '#71717a',
    themeSurfaceBgLight: '#f8f8f9',
    themeSurfaceBgDark: '#09090b',
    themeSurfaceBoxLight: '#ffffff',
    themeSurfaceBoxDark: '#18181b',
    themeBorderLight: '#e4e4e7',
    themeBorderDark: 'rgba(161, 161, 170, 0.22)',
    themeBorderDashedLight: '#d4d4d8',
    themeBorderDashedDark: 'rgba(161, 161, 170, 0.16)'
  },
  {
    id: 'mauve',
    name: 'Mauve',
    description: '冷紫灰，适合品牌化 SaaS',
    swatch: '#a59aa9',
    themeSurfaceBgLight: '#f7f4f8',
    themeSurfaceBgDark: '#120f15',
    themeSurfaceBoxLight: '#fffaff',
    themeSurfaceBoxDark: '#1F1C21',
    themeBorderLight: '#e5dbe9',
    themeBorderDark: 'rgba(216, 180, 254, 0.16)',
    themeBorderDashedLight: '#d8c8df',
    themeBorderDashedDark: 'rgba(216, 180, 254, 0.12)'
  },
  {
    id: 'olive',
    name: 'Olive',
    description: '柔和绿灰，适合数据和财务场景',
    swatch: '#8d967b',
    themeSurfaceBgLight: '#f4f7ef',
    themeSurfaceBgDark: '#0d1309',
    themeSurfaceBoxLight: '#fcfff8',
    themeSurfaceBoxDark: '#191D16',
    themeBorderLight: '#dce6d0',
    themeBorderDark: 'rgba(132, 204, 22, 0.16)',
    themeBorderDashedLight: '#cbdab9',
    themeBorderDashedDark: 'rgba(132, 204, 22, 0.12)'
  },
  {
    id: 'mist',
    name: 'Mist',
    description: '清透冷雾，适合现代产品工作台',
    swatch: '#9db5c3',
    themeSurfaceBgLight: '#f3f8fa',
    themeSurfaceBgDark: '#071216',
    themeSurfaceBoxLight: '#fbfdff',
    themeSurfaceBoxDark: '#171E22',
    themeBorderLight: '#d6e6ed',
    themeBorderDark: 'rgba(56, 189, 248, 0.14)',
    themeBorderDashedLight: '#c5dbe5',
    themeBorderDashedDark: 'rgba(56, 189, 248, 0.12)'
  },
  {
    id: 'taupe',
    name: 'Taupe',
    description: '稳重深灰褐，适合高密度业务',
    swatch: '#a9a29d',
    themeSurfaceBgLight: '#f5f3f1',
    themeSurfaceBgDark: '#12100e',
    themeSurfaceBoxLight: '#fffdfb',
    themeSurfaceBoxDark: '#1f1b18',
    themeBorderLight: '#e2dbd5',
    themeBorderDark: 'rgba(214, 211, 209, 0.16)',
    themeBorderDashedLight: '#d5cbc3',
    themeBorderDashedDark: 'rgba(214, 211, 209, 0.12)'
  },
  {
    id: 'raycast',
    name: 'Raycast',
    description: '近黑命令面板，适合开发者工具',
    swatch: '#ff6161',
    preferredThemeMode: 'dark',
    themeSurfaceBgLight: '#f4f4f6',
    themeSurfaceBgDark: '#07080a',
    themeSurfaceBoxLight: '#ffffff',
    themeSurfaceBoxDark: '#0d0d0d',
    themeBorderLight: '#e6e8eb',
    themeBorderDark: '#242728',
    themeBorderDashedLight: '#dfe3e8',
    themeBorderDashedDark: 'rgba(255,255,255,0.08)',
    themeBaseContent: '#f4f4f6',
    themeBaseContentLight: '#18191a',
    themeBaseContentDark: '#f4f4f6',
    themePrimary: '#ff6161',
    themePrimaryContent: '#ffffff',
    themeSecondary: '#57c1ff',
    themeSecondaryContent: '#000000',
    themeAccent: '#59d499',
    themeAccentContent: '#000000',
    themeNeutral: '#101111',
    themeNeutralContent: '#f4f4f6',
    themeInfo: '#57c1ff',
    themeInfoContent: '#000000',
    themeSuccess: '#59d499',
    themeSuccessContent: '#000000',
    themeWarning: '#ffc533',
    themeWarningContent: '#000000',
    themeError: '#ff6161',
    themeErrorContent: '#000000'
  },
  {
    id: 'linear',
    name: 'Linear',
    description: '近黑文档质感，适合研发协作',
    swatch: '#5e6ad2',
    preferredThemeMode: 'dark',
    themeSurfaceBgLight: '#f6f7f7',
    themeSurfaceBgDark: '#010102',
    themeSurfaceBoxLight: '#ffffff',
    themeSurfaceBoxDark: '#0f1011',
    themeBorderLight: '#e2e5ea',
    themeBorderDark: '#23252a',
    themeBorderDashedLight: '#d8dce4',
    themeBorderDashedDark: '#34343a',
    themeBaseContent: '#f7f8f8',
    themeBaseContentLight: '#000000',
    themeBaseContentDark: '#f7f8f8',
    themePrimary: '#5e6ad2',
    themePrimaryContent: '#ffffff',
    themeSecondary: '#7a7fad',
    themeSecondaryContent: '#ffffff',
    themeAccent: '#828fff',
    themeAccentContent: '#ffffff',
    themeNeutral: '#18191a',
    themeNeutralContent: '#f7f8f8',
    themeInfo: '#7a7fad',
    themeInfoContent: '#ffffff',
    themeSuccess: '#27a644',
    themeSuccessContent: '#ffffff',
    themeWarning: '#62666d',
    themeWarningContent: '#ffffff',
    themeError: '#8a8f98',
    themeErrorContent: '#ffffff'
  },
  {
    id: 'profound',
    name: 'Profound',
    description: '黑色剧场感，适合 AI 工作流',
    swatch: '#5DABFF',
    preferredThemeMode: 'dark',
    themeSurfaceBgLight: '#FBFCFD',
    themeSurfaceBgDark: '#050505',
    themeSurfaceBoxLight: '#FFFFFF',
    themeSurfaceBoxDark: '#141416',
    themeBorderLight: '#DDE5EA',
    themeBorderDark: '#292929',
    themeBorderDashedLight: '#C9D3DB',
    themeBorderDashedDark: 'rgba(255, 255, 255, 0.1)',
    themeBaseContent: '#F5F7FA',
    themeBaseContentLight: '#171717',
    themeBaseContentDark: '#F5F7FA',
    themePrimary: '#5DABFF',
    themePrimaryContent: '#FFFFFF',
    themeSecondary: '#08FFB6',
    themeSecondaryContent: '#00251d',
    themeAccent: '#935DFF',
    themeAccentContent: '#FFFFFF',
    themeNeutral: '#242426',
    themeNeutralContent: '#F5F7FA',
    themeInfo: '#5DABFF',
    themeInfoContent: '#FFFFFF',
    themeSuccess: '#05DF72',
    themeSuccessContent: '#002c17',
    themeWarning: '#FFEA35',
    themeWarningContent: '#292300',
    themeError: '#ED3A70',
    themeErrorContent: '#FFFFFF'
  },
  {
    id: 'searchable',
    name: 'Searchable',
    description: '暖米色平台感，适合 SEO 分析',
    swatch: '#C15F3C',
    preferredThemeMode: 'light',
    themeSurfaceBgLight: '#FDFBF9',
    themeSurfaceBgDark: '#1A0F13',
    themeSurfaceBoxLight: '#FFFFFF',
    themeSurfaceBoxDark: '#241B1D',
    themeBorderLight: '#E7E5E4',
    themeBorderDark: 'rgba(255, 255, 255, 0.12)',
    themeBorderDashedLight: '#D6D3D1',
    themeBorderDashedDark: 'rgba(255, 255, 255, 0.08)',
    themeBaseContent: '#1A0F13',
    themeBaseContentLight: '#1A0F13',
    themeBaseContentDark: '#FDFBF9',
    themePrimary: '#C15F3C',
    themePrimaryContent: '#FFFFFF',
    themeSecondary: '#A64E2A',
    themeSecondaryContent: '#FFFFFF',
    themeAccent: '#8B9D83',
    themeAccentContent: '#14200F',
    themeNeutral: '#3D3332',
    themeNeutralContent: '#FDFBF9',
    themeInfo: '#012169',
    themeInfoContent: '#FFFFFF',
    themeSuccess: '#059669',
    themeSuccessContent: '#052E16',
    themeWarning: '#D4A574',
    themeWarningContent: '#3D2107',
    themeError: '#C8102E',
    themeErrorContent: '#FFFFFF'
  },
  {
    id: 'unkey',
    name: 'Unkey',
    description: '暗色 API 基建，适合开发者控制台',
    swatch: '#03C2C3',
    preferredThemeMode: 'dark',
    themeSurfaceBgLight: '#FBFCFD',
    themeSurfaceBgDark: '#040406',
    themeSurfaceBoxLight: '#FFFFFF',
    themeSurfaceBoxDark: '#121317',
    themeBorderLight: '#E3E4E9',
    themeBorderDark: 'rgba(255, 255, 255, 0.1)',
    themeBorderDashedLight: '#C7C9D1',
    themeBorderDashedDark: 'rgba(255, 255, 255, 0.08)',
    themeBaseContent: '#FFFFFF',
    themeBaseContentLight: '#27272A',
    themeBaseContentDark: '#FFFFFF',
    themePrimary: '#03C2C3',
    themePrimaryContent: '#031B1A',
    themeSecondary: '#0095E6',
    themeSecondaryContent: '#FFFFFF',
    themeAccent: '#03C2C3',
    themeAccentContent: '#031B1A',
    themeNeutral: '#27272A',
    themeNeutralContent: '#FFFFFF',
    themeInfo: '#3580F1',
    themeInfoContent: '#FFFFFF',
    themeSuccess: '#10B981',
    themeSuccessContent: '#031B1A',
    themeWarning: '#C4D52E',
    themeWarningContent: '#262A03',
    themeError: '#EF4444',
    themeErrorContent: '#FFFFFF'
  },
  {
    id: 'duffel',
    name: 'Shadcn',
    description: 'shadcn 近黑风格，适合订单与 API',
    swatch: '#18181B',
    preferredThemeMode: 'light',
    themeSurfaceBgLight: '#FAFAFA',
    themeSurfaceBgDark: '#09090B',
    themeSurfaceBoxLight: '#FFFFFF',
    themeSurfaceBoxDark: '#18181B',
    themeBorderLight: '#E4E4E7',
    themeBorderDark: 'rgba(244, 244, 245, 0.12)',
    themeBorderDashedLight: '#D4D4D8',
    themeBorderDashedDark: 'rgba(244, 244, 245, 0.1)',
    themeBaseContent: '#18181B',
    themeBaseContentLight: '#18181B',
    themeBaseContentDark: '#FAFAFA',
    themePrimary: '#18181B',
    themePrimaryLight: '#18181B',
    themePrimaryDark: '#71717A',
    themePrimaryContent: '#FFFFFF',
    themePrimaryContentLight: '#FFFFFF',
    themePrimaryContentDark: '#FFFFFF',
    themeSecondary: '#3F4754',
    themeSecondaryContent: '#FFFFFF',
    themeAccent: '#3F746D',
    themeAccentContent: '#FFFFFF',
    themeNeutral: '#27272A',
    themeNeutralContent: '#FFFFFF',
    themeInfo: '#334155',
    themeInfoContent: '#FFFFFF',
    themeSuccess: '#3F746D',
    themeSuccessContent: '#FFFFFF',
    themeWarning: '#885928',
    themeWarningContent: '#FFFFFF',
    themeError: '#9E4C44',
    themeErrorContent: '#FFFFFF'
  },
  ...ART_THEME_PRESETS.map(createArtBasePalette)
]

export const THEME_ACCENT_PALETTES: ThemeAccentPalette[] = [
  { id: 'blue', name: 'Blue', color: '#377dff' },
  { id: 'purple', name: 'Purple', color: '#B387FA' },
  { id: 'green', name: 'Green', color: '#3f7d3f' },
  { id: 'rose', name: 'Rose', color: '#be123c' },
  { id: 'amber', name: 'Amber', color: '#c77800' },
  { id: 'teal', name: 'Teal', color: '#0f766e' },
  { id: 'neutral', name: 'Neutral', color: '#3f3f46' },
  { id: 'raycast', name: 'Raycast', color: '#ff6161' },
  { id: 'linear', name: 'Linear', color: '#5e6ad2' },
  { id: 'profound', name: 'Profound', color: '#5DABFF' },
  { id: 'searchable', name: 'Searchable', color: '#C15F3C' },
  { id: 'unkey', name: 'Unkey', color: '#03C2C3' },
  { id: 'duffel', name: 'Shadcn', color: '#18181B' },
  ...ART_THEME_PRESETS.map(createArtAccentPalette)
]

export const THEME_CHART_PALETTES: ThemeChartPalette[] = [
  {
    id: 'purple',
    name: 'Purple',
    colors: ['#B387FA', '#8b5cf6', '#f0a6d9', '#38bdf8', '#22c55e', '#f59e0b']
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    colors: ['#4A8BFF', '#14deba', '#ffaf20', '#4abeff', '#fa8a6c', '#ffaf20']
  },
  {
    id: 'sky',
    name: 'Sky',
    colors: ['#00A4F2', '#38bdf8', '#2563eb', '#14b8a6', '#f59e0b', '#f43f5e']
  },
  {
    id: 'blush',
    name: 'Blush',
    colors: ['#FF80C8', '#BE93F9', '#FFB86C', '#8BEAFD', '#51FA7C', '#F2FA8C']
  },
  {
    id: 'grove',
    name: 'Grove',
    colors: ['#16a34a', '#65a30d', '#0f766e', '#f59e0b', '#0284c7', '#dc2626']
  },
  {
    id: 'ember',
    name: 'Ember',
    colors: ['#be123c', '#f97316', '#f59e0b', '#7c3aed', '#0ea5e9', '#00d89f']
  },
  {
    id: 'mono',
    name: 'Mono',
    colors: ['#3f3f46', '#71717a', '#a1a1aa', '#52525b', '#27272a', '#d4d4d8']
  },
  {
    id: 'solar',
    name: 'Solar',
    colors: ['#F99120', '#fbbf24', '#00A4F2', '#8C50FF', '#14b8a6', '#f43f5e']
  },
  {
    id: 'raycast',
    name: 'Raycast',
    colors: ['#ff6161', '#57c1ff', '#59d499', '#ffc533', '#a1131a', '#9c9c9d']
  },
  {
    id: 'linear',
    name: 'Linear',
    colors: ['#5e6ad2', '#828fff', '#7a7fad', '#d0d6e0', '#62666d', '#27a644']
  },
  {
    id: 'profound',
    name: 'Profound',
    colors: ['#5DABFF', '#05DF72', '#08FFB6', '#935DFF', '#ED3A70', '#FFEA35']
  },
  {
    id: 'searchable',
    name: 'Searchable',
    colors: ['#C15F3C', '#A64E2A', '#D4A574', '#8B9D83', '#1A0F13', '#059669']
  },
  {
    id: 'unkey',
    name: 'Unkey',
    colors: ['#03C2C3', '#0095E6', '#C4D52E', '#27272A', '#9194A1', '#3580F1']
  },
  {
    id: 'duffel',
    name: 'Shadcn',
    colors: ['#737373', '#D4D4D4', '#525252', '#A3A3A3', '#404040', '#737373']
  },
  ...ART_THEME_PRESETS.map(createArtChartPalette)
]

export const THEME_STYLE_PRESETS: ThemeStylePreset[] = [
  {
    id: 'nova',
    name: 'Nova',
    description: '明快蓝调，适合标准产品后台',
    primary: '#377DFF',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.neutral,
    chartPaletteId: chartPalette.cobalt
  },
  {
    id: 'maia',
    name: 'Maia',
    description: '柔和紫调，适合协作套件',
    primary: '#B387FA',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.mauve,
    chartPaletteId: chartPalette.purple
  },
  {
    id: 'lyra',
    name: 'Lyra',
    description: '绿色增长感，适合数据与业务分析',
    primary: '#3f7d3f',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.olive,
    chartPaletteId: chartPalette.grove
  },
  {
    id: 'mira',
    name: 'Mira',
    description: '清亮蓝绿，适合运营中台',
    primary: '#00A4F2',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.mist,
    chartPaletteId: chartPalette.sky
  },
  {
    id: 'luma',
    name: 'Luma',
    description: '暖阳橙调，适合内容与营销空间',
    primary: '#F99120',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.stone,
    chartPaletteId: chartPalette.solar
  },
  {
    id: 'sera',
    name: 'Sera',
    description: '柔亮粉调，适合亲和型企业套件',
    primary: '#FF80C8',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.zinc,
    chartPaletteId: chartPalette.blush
  },
  {
    id: 'searchable',
    name: 'Searchable',
    description: '暖米画布与陶土橙，适合营销分析',
    primary: '#C15F3C',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.searchable,
    chartPaletteId: chartPalette.searchable,
    preferredThemeMode: 'light',
    semanticTokens: {
      themeBaseContent: '#1A0F13',
      themeBaseContentLight: '#1A0F13',
      themeBaseContentDark: '#FDFBF9',
      themePrimaryContent: '#FFFFFF',
      themeSecondary: '#A64E2A',
      themeSecondaryContent: '#FFFFFF',
      themeAccent: '#8B9D83',
      themeAccentContent: '#14200F',
      themeNeutral: '#3D3332',
      themeNeutralContent: '#FDFBF9',
      themeInfo: '#012169',
      themeInfoContent: '#FFFFFF',
      themeSuccess: '#059669',
      themeSuccessContent: '#052E16',
      themeWarning: '#D4A574',
      themeWarningContent: '#3D2107',
      themeError: '#C8102E',
      themeErrorContent: '#FFFFFF'
    }
  },
  {
    id: 'unkey',
    name: 'Unkey',
    description: '近黑画布与 cyan 高亮，适合 API 平台',
    primary: '#03C2C3',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.unkey,
    chartPaletteId: chartPalette.unkey,
    preferredThemeMode: 'dark',
    semanticTokens: {
      themeBaseContent: '#FFFFFF',
      themeBaseContentLight: '#27272A',
      themeBaseContentDark: '#FFFFFF',
      themePrimaryContent: '#031B1A',
      themeSecondary: '#0095E6',
      themeSecondaryContent: '#FFFFFF',
      themeAccent: '#03C2C3',
      themeAccentContent: '#031B1A',
      themeNeutral: '#27272A',
      themeNeutralContent: '#FFFFFF',
      themeInfo: '#3580F1',
      themeInfoContent: '#FFFFFF',
      themeSuccess: '#10B981',
      themeSuccessContent: '#031B1A',
      themeWarning: '#C4D52E',
      themeWarningContent: '#262A03',
      themeError: '#EF4444',
      themeErrorContent: '#FFFFFF'
    }
  },
  {
    id: 'duffel',
    name: 'Shadcn',
    description: 'shadcn 近黑 CTA，适合订单工具',
    primary: '#18181B',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.duffel,
    chartPaletteId: chartPalette.duffel,
    preferredThemeMode: 'light',
    semanticTokens: {
      themeBaseContent: '#18181B',
      themeBaseContentLight: '#18181B',
      themeBaseContentDark: '#FAFAFA',
      themePrimaryLight: '#18181B',
      themePrimaryDark: '#71717A',
      themePrimaryContent: '#FFFFFF',
      themePrimaryContentLight: '#FFFFFF',
      themePrimaryContentDark: '#FFFFFF',
      themeSecondary: '#3F4754',
      themeSecondaryContent: '#FFFFFF',
      themeAccent: '#3F746D',
      themeAccentContent: '#FFFFFF',
      themeNeutral: '#27272A',
      themeNeutralContent: '#FFFFFF',
      themeInfo: '#334155',
      themeInfoContent: '#FFFFFF',
      themeSuccess: '#3F746D',
      themeSuccessContent: '#FFFFFF',
      themeWarning: '#9A5A16',
      themeWarningContent: '#FFFFFF',
      themeError: '#B33A2E',
      themeErrorContent: '#FFFFFF',
      themeMenuHoverMixLight: '4%',
      themeMenuActiveBgMixLight: '10%'
    }
  },
  {
    id: 'raycast',
    name: 'Raycast',
    description: '纯黑命令面板，适合开发者工具',
    primary: '#ff6161',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.raycast,
    chartPaletteId: chartPalette.raycast,
    preferredThemeMode: 'dark',
    semanticTokens: {
      themeBaseContent: '#f4f4f6',
      themeBaseContentLight: '#18191a',
      themeBaseContentDark: '#f4f4f6',
      themePrimaryContent: '#ffffff',
      themeSecondary: '#57c1ff',
      themeSecondaryContent: '#000000',
      themeAccent: '#59d499',
      themeAccentContent: '#000000',
      themeNeutral: '#101111',
      themeNeutralContent: '#f4f4f6',
      themeInfo: '#57c1ff',
      themeInfoContent: '#000000',
      themeSuccess: '#59d499',
      themeSuccessContent: '#000000',
      themeWarning: '#ffc533',
      themeWarningContent: '#000000',
      themeError: '#ff6161',
      themeErrorContent: '#000000'
    }
  },
  {
    id: 'linear',
    name: 'Linear',
    description: '近黑画布与蓝紫主色，适合研发协作',
    primary: '#5e6ad2',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.linear,
    chartPaletteId: chartPalette.linear,
    preferredThemeMode: 'dark',
    semanticTokens: {
      themeBaseContent: '#f7f8f8',
      themeBaseContentLight: '#000000',
      themeBaseContentDark: '#f7f8f8',
      themePrimaryContent: '#ffffff',
      themeSecondary: '#7a7fad',
      themeSecondaryContent: '#ffffff',
      themeAccent: '#828fff',
      themeAccentContent: '#ffffff',
      themeNeutral: '#18191a',
      themeNeutralContent: '#f7f8f8',
      themeInfo: '#7a7fad',
      themeInfoContent: '#ffffff',
      themeSuccess: '#27a644',
      themeSuccessContent: '#ffffff',
      themeWarning: '#62666d',
      themeWarningContent: '#ffffff',
      themeError: '#8a8f98',
      themeErrorContent: '#ffffff'
    }
  },
  {
    id: 'profound',
    name: 'Profound',
    description: '黑色剧场与电光蓝，适合 AI 工作流',
    primary: '#5DABFF',
    radius: '0.5',
    boxBorderMode: true,
    basePaletteId: basePalette.profound,
    chartPaletteId: chartPalette.profound,
    preferredThemeMode: 'dark',
    semanticTokens: {
      themeBaseContent: '#F5F7FA',
      themeBaseContentLight: '#171717',
      themeBaseContentDark: '#F5F7FA',
      themePrimaryContent: '#FFFFFF',
      themeSecondary: '#08FFB6',
      themeSecondaryContent: '#00251d',
      themeAccent: '#935DFF',
      themeAccentContent: '#FFFFFF',
      themeNeutral: '#242426',
      themeNeutralContent: '#F5F7FA',
      themeInfo: '#5DABFF',
      themeInfoContent: '#FFFFFF',
      themeSuccess: '#05DF72',
      themeSuccessContent: '#002c17',
      themeWarning: '#FFEA35',
      themeWarningContent: '#292300',
      themeError: '#ED3A70',
      themeErrorContent: '#FFFFFF'
    }
  },
  ...ART_THEME_PRESETS.map(createArtStylePreset)
]

export const THEME_RADIUS_OPTIONS: ThemeRadiusOption[] = [
  { id: 'none', name: 'None', value: '0' },
  { id: 'small', name: 'Small', value: '0.25' },
  { id: 'medium', name: 'Medium', value: '0.5' },
  { id: 'large', name: 'Large', value: '0.75' },
  { id: 'round', name: 'Round', value: '1' }
]
