import { prisma } from '../../utils/prisma';
import { ApiError } from '../../utils/api-error';
import { paginatedResult } from '../../utils/pagination';
export async function getUserList(page=1, size=20, keyword?: string) { const where = keyword ? { OR: [{ uid: { contains: keyword } }, { nickname: { contains: keyword } }] } : {}; const [list, total] = await Promise.all([prisma.user.findMany({ where, skip: (page-1)*size, take: size, orderBy: { createdAt: 'desc' } }), prisma.user.count({ where })]); return paginatedResult(list, total, page, size); }
export async function getUserDetail(id: number) { const u = await prisma.user.findUnique({ where: { id } }); if (!u) throw new ApiError(40003, '用户不存在'); return u; }
export async function updateUser(id: number, data: any) { await prisma.user.update({ where: { id }, data }); return getUserDetail(id); }
export async function deleteUser(id: number) { await prisma.user.delete({ where: { id } }); return true; }
export async function getAuthApplications(page=1, size=20, status?: string) { const where = status ? { status } : {}; const [list, total] = await Promise.all([prisma.authApplication.findMany({ where, skip: (page-1)*size, take: size, orderBy: { createdAt: 'desc' } }), prisma.authApplication.count({ where })]); return paginatedResult(list, total, page, size); }
export async function reviewAuthApplication(id: number, status: string, reviewRemark: string) { const app = await prisma.authApplication.findUnique({ where: { id } }); if (!app) throw new ApiError(40003, '申请不存在'); await prisma.authApplication.update({ where: { id }, data: { status, reviewRemark, reviewedAt: new Date() } }); if (status === 'approved') { await prisma.user.update({ where: { id: app.userId }, data: { authStatus: 'verified', pointsEnabled: true, points: { increment: 10 } } }); await prisma.pointsLog.create({ data: { userId: app.userId, points: 10, reason: '认证通过' } }); await prisma.notification.create({ data: { typeId: 1, title: '认证已通过', content: '你的身份认证已通过，积分已开启并获得10积分奖励。', target: 'all' } }); } else if (status === 'rejected') { await prisma.authApplication.update({ where: { id }, data: { rejectCount: { increment: 1 } } }); await prisma.user.update({ where: { id: app.userId }, data: { authStatus: 'unverified' } }); } return true; }
// 认证申请详情
export async function getAuthApplicationDetail(id: number) { const a = await prisma.authApplication.findUnique({ where: { id } }); if (!a) throw new ApiError(40003, '申请不存在'); return a; }
