allowBuilds:
  '@parcel/watcher': set this to true or false
  '@tailwindcss/oxide': true
  core-js: set this to true or false
  es5-ext: set this to true or false
  esbuild: true
  vue-demi: set this to true or false
