import Router from 'koa-router';
import * as ctrl from '../controllers/auth.controller';
import { rateLimitLogin } from '../middlewares/rate-limit.middleware';
import { loginLogMiddleware } from '../middlewares/log.middleware';
const router = new Router({ prefix: '/api/v1/auth' });
router.post('/register', ctrl.register);
router.post('/login', rateLimitLogin, loginLogMiddleware, ctrl.login);
router.post('/refresh', ctrl.refresh);
router.post('/admin/login', rateLimitLogin, loginLogMiddleware, ctrl.adminLogin);
export default router;
