/**
 * 海大工坊 · 网页端图标注册表
 * 全站统一 Lucide 图标，界面禁止使用 emoji。
 * 业务语义名 → lucide 图标组件（命名导入，按需 tree-shake）。
 * 新增图标：在此注册表追加，勿在页面内直接散用 emoji 或裸 lucide 名。
 */
import {
  Home,
  GraduationCap,
  School,
  ShoppingBag,
  CalendarDays,
  CalendarRange,
  Wrench,
  Phone,
  MapPin,
  Bus,
  Newspaper,
  Users,
  Heart,
  BookOpen,
  Compass,
  HelpCircle,
  MessageSquare,
  Bell,
  User,
  Settings,
  LogOut,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Plus,
  AlertTriangle,
  Check,
  Copy,
  Share2,
  Trash2,
  Search,
  Send,
  Upload,
  Image as ImageIcon,
  Star,
  ThumbsUp,
  MessageCircle,
  Clock,
  Menu,
  Filter,
  RefreshCw,
  Download,
  Eye,
  EyeOff,
  Pencil,
  Camera,
  Gift,
  Sparkles,
  Award,
  Flag,
  Mail,
  Lock,
  Package,
  Library,
  Printer,
  Backpack,
  Building2,
  Dices,
  Play,
  Calculator,
  Target,
  Delete,
  Timer,
  ArrowLeftRight,
  Quote,
} from 'lucide-vue-next'
import type { Component } from 'vue'

/** 图标组件类型（lucide 图标均为 Vue 组件） */
export type IconComponent = Component

/** 业务语义名 → lucide 图标组件 */
export const iconRegistry = {
  /* —— 顶部导航 / 专区 —— */
  'nav-home': Home,
  'zone-freshman': GraduationCap,
  'zone-student': School,

  /* —— 模块入口（替代 Home 宫格 / LifeTopics / Tools 的 emoji） —— */
  'module-marketplace': ShoppingBag,
  'module-calendar': CalendarRange,
  'module-schedule': CalendarDays,
  'module-tools': Wrench,
  'module-phonebook': Phone,
  'module-map': MapPin,
  'module-bus': Bus,
  'module-news': Newspaper,
  'module-alumni': Users,
  'module-confession': Heart,
  'module-intro': BookOpen,
  'module-guide': Compass,
  'module-life': BookOpen,
  'module-faq': HelpCircle,
  'module-roommate': Users,

  /* —— 生活主题（替代 LifeTopics 原 emoji 图标） —— */
  'life-canteen': Package,
  'life-express': Package,
  'life-shop': ShoppingBag,
  'life-hospital': Plus,
  'life-sport': Award,
  'life-print': Printer,
  'life-bus': Bus,

  /* —— 校区 / 介绍 —— */
  'campus': Building2,
  'campus-library': Library,
  'campus-backpack': Backpack,

  /* —— 工具箱子组件 —— */
  'tool-dice': Dices,
  'tool-play': Play,
  'tool-calculator': Calculator,
  'tool-wheel': Target,
  'tool-backspace': Delete,
  'tool-timer': Timer,
  'tool-image': ImageIcon,
  'tool-camera': Camera,

  /* —— 用户 / 账号 —— */
  'action-feedback': MessageSquare,
  'action-bell': Bell,
  'action-profile': User,
  'action-settings': Settings,
  'action-logout': LogOut,
  'action-login': LogOut,

  /* —— 通用操作 —— */
  'arrow-right': ChevronRight,
  'arrow-left': ChevronLeft,
  'arrow-down': ChevronDown,
  'arrow-up': ChevronUp,
  'close': X,
  'add': Plus,
  'warning': AlertTriangle,
  'check': Check,
  'copy': Copy,
  'share': Share2,
  'trash': Trash2,
  'search': Search,
  'send': Send,
  'upload': Upload,
  'star': Star,
  'like': ThumbsUp,
  'comment': MessageCircle,
  'clock': Clock,
  'menu': Menu,
  'filter': Filter,
  'refresh': RefreshCw,
  'download': Download,
  'eye': Eye,
  'eye-off': EyeOff,
  'edit': Pencil,
  'quote': Quote,

  /* —— 奇幻 / 装饰点缀（访客首页 mascot 等，≤5%） —— */
  'fantasy-gift': Gift,
  'fantasy-sparkles': Sparkles,
  'fantasy-award': Award,
  'fantasy-flag': Flag,
  'mail': Mail,
  'lock': Lock,
  'swap': ArrowLeftRight,
} as const satisfies Record<string, IconComponent>

export type IconName = keyof typeof iconRegistry
