import { prisma } from '../utils/prisma';
import { ApiError } from '../utils/api-error';
import { paginatedResult } from '../utils/pagination';
export async function getSections() { return prisma.alumniSection.findMany({ where: { isActive: true }, orderBy: { sortOrder: 'asc' } }); }
export async function getPosts(type: string, sectionId: number|undefined, page = 1, size = 20) { const where: any = { isActive: true, type }; if (sectionId) where.sectionId = sectionId; const orderBy: any = type === 'post' ? [{ isPinned: 'desc' as const }, { createdAt: 'desc' as const }] : [{ createdAt: 'desc' as const }]; const [list, total] = await Promise.all([prisma.alumniPost.findMany({ where, skip: (page-1)*size, take: size, orderBy }), prisma.alumniPost.count({ where })]); return paginatedResult(list, total, page, size); }
export async function getPost(id: number) { const p = await prisma.alumniPost.findUnique({ where: { id } }); if (!p || !p.isActive) throw new ApiError(40003, '内容不存在'); return p; }
export async function createPost(userId: number, data: any) { return prisma.alumniPost.create({ data: { userId, ...data, images: data.images || undefined } }); }
export async function deletePost(id: number, userId: number) { const p = await prisma.alumniPost.findUnique({ where: { id } }); if (!p) throw new ApiError(40003, '内容不存在'); if (p.userId !== userId) throw new ApiError(40004, '无权操作'); return prisma.alumniPost.delete({ where: { id } }); }
export async function likePost(postId: number, userId: number) { const e = await prisma.alumniLike.findUnique({ where: { postId_userId: { postId, userId } } }); if (e) throw new ApiError(40001, '已点赞'); await prisma.$transaction([prisma.alumniLike.create({ data: { postId, userId } }), prisma.alumniPost.update({ where: { id: postId }, data: { likeCount: { increment: 1 } } })]); return true; }
export async function unlikePost(postId: number, userId: number) { await prisma.$transaction([prisma.alumniLike.deleteMany({ where: { postId, userId } }), prisma.alumniPost.update({ where: { id: postId }, data: { likeCount: { decrement: 1 } } })]); return true; }
export async function getComments(postId: number, page = 1, size = 50) { const [list, total] = await Promise.all([prisma.alumniComment.findMany({ where: { postId }, skip: (page-1)*size, take: size, orderBy: { createdAt: 'asc' } }), prisma.alumniComment.count({ where: { postId } })]); return paginatedResult(list, total, page, size); }
export async function createComment(postId: number, userId: number, data: any) { const c = await prisma.alumniComment.create({ data: { postId, userId, ...data } }); await prisma.alumniPost.update({ where: { id: postId }, data: { commentCount: { increment: 1 }, lastCommentAt: new Date() } }); return c; }
export async function deleteComment(id: number, userId: number) { const c = await prisma.alumniComment.findUnique({ where: { id } }); if (!c) throw new ApiError(40003, '评论不存在'); if (c.userId !== userId) throw new ApiError(40004, '无权操作'); await prisma.alumniComment.delete({ where: { id } }); await prisma.alumniPost.update({ where: { id: c.postId }, data: { commentCount: { decrement: 1 } } }); return true; }
export async function reportPost(targetId: number, reporterUserId: number, reason: string, detail?: string) { return prisma.report.create({ data: { targetType: 'post', targetId, reporterUserId, reason, detail: detail||null } }); }
export async function reportComment(targetId: number, reporterUserId: number, reason: string, detail?: string) { return prisma.report.create({ data: { targetType: 'comment', targetId, reporterUserId, reason, detail: detail||null } }); }
