import { prisma } from '../utils/prisma';
import { ApiError } from '../utils/api-error';
import { paginatedResult } from '../utils/pagination';
export async function getCategories() { return prisma.marketplaceCategory.findMany({ where: { isActive: true }, orderBy: { sortOrder: 'asc' } }); }
export async function getItems(categoryId?: number, keyword?: string, page = 1, size = 20) { const where: any = { status: 'active' }; if (categoryId) where.categoryId = Number(categoryId); if (keyword) where.title = { contains: keyword }; const [list, total] = await Promise.all([prisma.marketplaceItem.findMany({ where, skip: (page-1)*size, take: size, orderBy: { publishedAt: 'desc' }, include: { category: true } }), prisma.marketplaceItem.count({ where })]); return paginatedResult(list, total, page, size); }
export async function getItem(id: number) { const i = await prisma.marketplaceItem.findUnique({ where: { id }, include: { category: true } }); if (!i) throw new ApiError(40003, '商品不存在'); await prisma.marketplaceItem.update({ where: { id }, data: { viewCount: { increment: 1 } } }); return i; }
export async function createItem(userId: number, identity: string, data: any) { const now = new Date(); const autoOffAt = new Date(now.getTime() + 3*86400000); const expireAt = new Date(now.getTime() + 5*86400000); return prisma.marketplaceItem.create({ data: { userId, userIdentity: identity, title: data.title, description: data.description||null, price: data.price, images: data.images, contact: data.contact, categoryId: data.categoryId, status: 'active', publishedAt: now, autoOffAt, expireAt } }); }
export async function offItem(id: number, userId: number) { const i = await prisma.marketplaceItem.findUnique({ where: { id } }); if (!i) throw new ApiError(40003, '商品不存在'); if (i.userId !== userId) throw new ApiError(40004, '无权操作'); return prisma.marketplaceItem.update({ where: { id }, data: { status: 'auto_off' } }); }
export async function deleteItem(id: number, userId: number) { const i = await prisma.marketplaceItem.findUnique({ where: { id } }); if (!i) throw new ApiError(40003, '商品不存在'); if (i.userId !== userId) throw new ApiError(40004, '无权操作'); return prisma.marketplaceItem.delete({ where: { id } }); }
export async function relistItem(id: number, userId: number) { const i = await prisma.marketplaceItem.findUnique({ where: { id } }); if (!i) throw new ApiError(40003, '商品不存在'); if (i.userId !== userId) throw new ApiError(40004, '无权操作'); if (i.expireAt && new Date(i.expireAt) < new Date()) throw new ApiError(40001, '商品已过期'); const now = new Date(); return prisma.marketplaceItem.update({ where: { id }, data: { status: 'active', publishedAt: now, autoOffAt: new Date(now.getTime()+3*86400000), expireAt: new Date(now.getTime()+5*86400000) } }); }
export async function getMyItems(userId: number, page = 1, size = 20) { const [list, total] = await Promise.all([prisma.marketplaceItem.findMany({ where: { userId }, skip: (page-1)*size, take: size, orderBy: { publishedAt: 'desc' } }), prisma.marketplaceItem.count({ where: { userId } })]); return paginatedResult(list, total, page, size); }
export async function reportItem(targetId: number, reporterUserId: number, reason: string, detail?: string) { return prisma.report.create({ data: { targetType: 'item', targetId, reporterUserId, reason, detail: detail||null } }); }
