import { prisma } from '../utils/prisma';
import { ApiError } from '../utils/api-error';
import { paginatedResult } from '../utils/pagination';
export async function getStatus() { const s = await prisma.roommateSetting.findFirst(); if (!s) return { isOpen: false, startDate: null, endDate: null }; const now = new Date(); const isOpen = s.isEnabled && s.startDate && s.endDate && now >= s.startDate && now <= s.endDate; return { isOpen, startDate: s.startDate, endDate: s.endDate }; }
export async function createPost(userId: number, data: any) { const existing = await prisma.roommatePost.findUnique({ where: { userId } }); if (existing) throw new ApiError(40009, '已存在发布信息'); return prisma.roommatePost.create({ data: { userId, ...data } }); }
export async function getMyPost(userId: number) { return prisma.roommatePost.findUnique({ where: { userId } }); }
export async function updatePost(userId: number, data: any) { const p = await prisma.roommatePost.findUnique({ where: { userId } }); if (!p) throw new ApiError(40003, '发布信息不存在'); const s = await prisma.roommateSetting.findFirst(); if (p.modifyCount >= (s?.maxModifyCount || 3)) throw new ApiError(40008, '修改次数已用完'); return prisma.roommatePost.update({ where: { userId }, data: { ...data, modifyCount: { increment: 1 } } }); }
export async function getPosts(page = 1, size = 20) { const [list, total] = await Promise.all([prisma.roommatePost.findMany({ where: { isActive: true }, skip: (page-1)*size, take: size, orderBy: { createdAt: 'desc' } }), prisma.roommatePost.count({ where: { isActive: true } })]); return paginatedResult(list, total, page, size); }
export async function getPost(id: number) { const p = await prisma.roommatePost.findUnique({ where: { id } }); if (!p) throw new ApiError(40003, '信息不存在'); return p; }
export async function matchPosts(userId: number, data: any) { const rm = await prisma.roommatePost.findMany({ where: { isActive: true, userId: { not: userId }, campusId: data.campusId, collegeId: data.collegeId, buildingId: data.buildingId, roomNumber: data.roomNumber } }); const mm = await prisma.roommatePost.findMany({ where: { isActive: true, userId: { not: userId }, departmentId: data.departmentId, majorId: data.majorId } }); return { roommateMatches: rm, majorMatches: mm, hasRoommate: rm.length > 0, hasMajorMatch: mm.length > 0 }; }
