import { prisma } from '../utils/prisma';
import { ApiError } from '../utils/api-error';
import { hashPassword, verifyPassword, maybeUpgrade } from '../utils/password';
export async function getProfile(userId: number) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); return { uid: u.uid, nickname: u.nickname, avatar: u.avatar, email: u.email, qq: u.qq, wechat: u.wechat, identity: u.identity, authStatus: u.authStatus, pointsEnabled: u.pointsEnabled, points: u.points, privacyEnabled: u.privacyEnabled }; }
export async function updateProfile(userId: number, data: any) { await prisma.user.update({ where: { id: userId }, data }); return getProfile(userId); }
export async function changePassword(userId: number, oldP: string, newP: string) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); const { valid, needsUpgrade } = verifyPassword(oldP, u.passwordHash); if (!valid) throw new ApiError(40001, '原密码错误'); await prisma.user.update({ where: { id: userId }, data: { passwordHash: hashPassword(newP) } }); return true; }
export async function getPublicProfile(uid: string) { const u = await prisma.user.findUnique({ where: { uid } }); if (!u) throw new ApiError(40003, '用户不存在'); const info: any = { uid: u.uid, nickname: u.nickname, avatar: u.avatar }; if (!u.privacyEnabled) { info.email = u.email; info.qq = u.qq; info.wechat = u.wechat; info.identity = u.identity; } else { const f = u.privacyFields as any || {}; if (f.email) info.email = u.email; if (f.qq) info.qq = u.qq; if (f.wechat) info.wechat = u.wechat; if (f.identity) info.identity = u.identity; } return info; }
export async function getPrivacy(userId: number) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); return { privacyEnabled: u.privacyEnabled, privacyFields: u.privacyFields || {} }; }
export async function updatePrivacy(userId: number, privacyEnabled: boolean, privacyFields: any) { await prisma.user.update({ where: { id: userId }, data: { privacyEnabled, privacyFields } }); return getPrivacy(userId); }
export async function submitAuthApply(userId: number, data: { realName: string; studentNo: string; major: string; proofImage: string }) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); const rc = await prisma.authApplication.count({ where: { userId, status: 'rejected' } }); if (rc >= 3) throw new ApiError(40004, '认证申请次数已用完'); await prisma.authApplication.create({ data: { userId, realName: data.realName, studentNo: data.studentNo, major: data.major, proofImage: data.proofImage, status: 'pending', rejectCount: rc } }); await prisma.user.update({ where: { id: userId }, data: { authStatus: 'pending' } }); return true; }
export async function getAuthStatus(userId: number) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); const last = await prisma.authApplication.findFirst({ where: { userId }, orderBy: { createdAt: 'desc' } }); return { authStatus: u.authStatus, rejectCount: last?.rejectCount || 0, reviewRemark: last?.reviewRemark || null }; }
export async function getPoints(userId: number) { const u = await prisma.user.findUnique({ where: { id: userId } }); if (!u) throw new ApiError(40003, '用户不存在'); return { pointsEnabled: u.pointsEnabled, points: u.points }; }
